site_name: 痞老板的notebook
site_url: https://wiki.yourdomain.com
site_author: Your Name

theme:
  name: material
  icon: 
    logo: material/notebook-outline
  custom_dir: overrides
  language: zh
  # 恢复标准的日间/夜间切换功能
  font: false 
  
  palette:
    # 1. 默认深色模式 (排在第一位，所以一打开网页就是夜间模式)
    - scheme: slate
      primary: indigo   # 你的主色调，可以自己改
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  # 保持好用的功能
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - statistics: # <--- 启用统计插件，否则 {{ pages }} 会直接显示字符
      enabled: true

extra_css:
  - stylesheets/extra.css

# 【重点 3】Markdown 扩展支持
markdown_extensions:
  - admonition
  - attr_list         # 必须开启！否则无法使用 .card 等自定义 CSS 类
  - md_in_html        # 允许在 HTML 标签中写 Markdown，配合 Card 使用
  - pymdownx.details  # 折叠块
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true # 开启自定义复选框样式
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons  # 允许你自己上传图标
  

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Physics:
    - 量子力学: physics/quantum.md
    - 电磁学: physics/electromagnetism.md
  - Computer Science:
    - 数据结构: coding/ds.md
    - 算法笔记: coding/algo.md
  - Friends: friends.md

repo_url: https://github.com/Mr2025x/my-wiki  # 加上这行激活右上角区域

extra:
  social:
    
    # 2. 导航键 (指南针图标)
    - icon: fontawesome/solid/compass
      link: https://plankton2005.best # 【请替换为你真实的 Navigation 链接】
      name: 导航 (Navigation)
      
    # 3. Blog 键 (博客图标)
    - icon: fontawesome/solid/blog
      link: https://blog.plankton2005.best # 【请替换为你真实的 Blog 链接】
      name: 博客 (Blog)
      
    # 4. 友链键 (人群图标)
    - icon: fontawesome/solid/user-group
      link: https://plankton2005.best/friends # 【请替换为真实的友链地址】
      name: 友链 (Friends)
      
    # 5. 留言板键 (留言气泡图标)
    - icon: fontawesome/solid/comments
      link: https://plankton2005.best/guestbook # 【请替换为真实的留言板地址】
      name: 留言板 (Guestbook)